version: '3.8'

services:
  websocket-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: websocket-filter-service
    container_name: websocket-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - websocket-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

 

networks:
  websocket-network:
    driver: bridge